### PR TITLE
Add UTF8 character set

### LINKED ISSUE #2: [Tumbleweed] unbootable system with dracut-pcr-signatures
I tried to add measured boot to Tumbleweed, but the system is now unbootable with the module included as the https://github.com/aplanas/dracut-pcr-signature/blob/main/pcr-signature.sh script fails when running systemd-cryptsetup@cr_root.service. The service has been replaced by a link to that script.
The script fails as the command "mktemp" isn't available in my initrm stage. I could workaround this by deleting the service override (this made the system bootable again) and then I deactivated the module.

Can this behaviour be replicated?

### PR DESCRIPTION
**Pull request by TobiPeterG**
fixes #2

### CODE REVIEW

**Comment by aplanas** [comment]
That was the same fix that I would try. Did you tested it?

**Comment by TobiPeterG** [comment]
> That was the same fix that I would try. Did you tested it?

Yes, my system boots now :)

What character sets are even possible for an EFI partition?

**Comment by aplanas** [comment]
> What character sets are even possible for an EFI partition?

With `--codepage` you can select the module, and my system has around 50 code pages in the native language support (nls) directory. But by default only `iso8859` is used, did you formatted the EFI partition yourself?

**Review by aplanas — APPROVED** [review]

**Comment by TobiPeterG** [comment]
> > What character sets are even possible for an EFI partition?
> 
> With `--codepage` you can select the module, and my system has around 50 code pages in the native language support (nls) directory. But by default only `iso8859` is used, did you formatted the EFI partition yourself?

No, I used the Tumbleweed install ISO to format them.

**Pull request merged**
